### ISSUE TITLE
Decide on controlled subject vocabularies and subject fields

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#16]

**Comment by bjr70** [comment]
No DDC. 😆 I do want to keep the FOS vocabulary that came with Invenio and add MESH. NASA looks good too. I also want to add Homosaurus -  https://homosaurus.org/ - an international linked data vocabulary of Lesbian, Gay, Bisexual, Transgender, and Queer (LGBTQ) terms.

Lucas found the following when I asked about indigenous vocabularies and I'd like to consider these: 
- New Zealand https://natlib.govt.nz/librarians/nga-upoko-tukutuku#about-the-project
- Australia https://www1.aiatsis.gov.au/ThesaurusDownload.html
- First Nations Metis and Inuit Indigenous Ontology (Canada) https://www.nikla-ancla.com/post/first-nations-metis-and-inuit-indigenous-ontologies-fnmiio (has a link to a Google sheet)

Not sure about this one. It's in Chinese. Could be helpful, but not sure what the implications would be. 
- Ethnic group names (from Taiwan Central Library, in Chinese) https://catweb.ncl.edu.tw/subject2005/hs_appendix4.pdf
- 
It looks like the GND is in German? Not sure about that one, either. 

If anyone is interested in controlled vocabularies BARTOC has a searchable database: https://bartoc.org/vocabularies?languages=en.
