### ISSUE TITLE
Implement custom fields in Invenio JSON schema

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#17]

**Comment by monotasker** [comment]
To do
[ ] Convert genre and publication_type core fields to fit new deposit types

**Comment by rekmla** [comment]
@monotasker, text **is** sanitized in the fields named "_unchanged" - several safe tags are allowed such as ```<b>```. Further modifications are made to title, abstract and notes to strip the allowed markup prior to creating things like the MODS record.

**Comment by monotasker** [comment]
Ah, okay. Thanks for the clarification @rekmla . So can you tell me exactly what is being stripped out? I want to figure out whether we need to retain that field or whether it's redundant in Invenio. (Internally InvenioRDM doesn't have any equivalent stripped fields.)

**Comment by rekmla** [comment]
title, abstract and notes fields get sanitized with the WP function sanitize_text_field.

Users asked to be able to enter b, em or strong and so the 3 fields with the _unchanged suffix are sanitized with the WP function wp_kses.

"abstract_unchanged" is displayed on the Commons, but I believe "abstract" is passed to Fedora, Datacite, Google Scholar, Ppen Graph tags, OAI-PMH
