### ISSUE TITLE
Develop plan for metrics reporting

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/knowledge-commons-repository#197]
[ ] Collect list of metrics desired for the Invenio dashboard
[ ] Determine which metrics can be obtained using existing REST API

**Comment by monotasker** [comment]
Initial list of metrics:

- Total deposits
- No. deposits tracked over time
- No. views per deposit
- No. downloads per deposit
- Average views per deposit + over time
- Average downloads per deposit + over time
- List of top deposits by download
- No. deposits by member
- No. deposits by identified institution (ROR)
- Average no. deposits per user + over time
- No. deposits removed over time
- List of users with most deposits
- Eventually moderation statistics here too

**Comment by koutiany** [comment]
Just a quick note: it seems that "stats" also consider "versions."

"stats": {

                    "all_versions": {

                        "unique_views": 0,

                        "views": 0,

                        "unique_downloads": 0,

                        "downloads": 0,

                        "data_volume": 0.0

                    },

                    "this_version": {

                        "unique_views": 0,

                        "views": 0,

                        "unique_downloads": 0,

                        "downloads": 0,

                        "data_volume": 0.0

                    }

               }"

Should we take that into consideration?

**Comment by koutiany** [comment]
Cassie's [summary](https://docs.google.com/document/d/1xNXPAU_5UDir_WlsRyhySWgpkCaO7WowSrqWWZPvREg/edit?usp=sharing) on invenio stats.
