### ISSUE TITLE
Implement Commons API endpoint for user data

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#208]
We need to implement an API endpoint on the Commons that serves user data to Invenio. 

Could be something like:

hcommons.org/api/members/<member_id>

With a JSON response object.

This is assuming 
1. we're *not* querying an ActivityPub outbox. (since that would be for activity events?)
2. we're *not* providing information about activity (e.g., recent activity) (since we'll publish that with ActivityPub outbox?)

**Comment by monotasker** [comment]
Current (projected) format for JSON responses is an object with keys for data to be updated:

```
{'id': 'my_commons_id',
 'groups': [{'name': 'awesome-mock2'},
                   {'name': 'admin'}]
 }
```
Response is stateless. Not changes, but the current state of user's data on Commons. (So 'groups' gives complete current list of groups.)

**Comment by mikethicke** [comment]
Endpoint is at https://hcommons-dev.org/wp-json/commons/v1/users/:username .

The API is using token authentication, so you need to set the authorization header to `Bearer <token>` . Token is set in .env .

Response format:

```
{
    "username": "<WordPress username>",
    "email": "<registered email>",
    "name": "<WordPress display name>",
    "first_name": "<first name>",
    "last_name": "<last name>",
    "institutional_affiliation": "<affiliation---only one value is tracked>",
    "groups": [
        {
            "id": <group_id (int)>,
            "name": "<group display name>",
            "role": "<member|moderator|admin>" (Note: We don't actually seem to use the moderator role, though it exists)
        },
        {
            "id": 1002890,
            "name": "MDPx",
            "role": "member"
        },
       ....
}
```

Notes:

- We don't track group types in the way reflected above, though if desired we could return what Organization the group belongs to.
- We don't track multiple affiliations
- We don't track preferred language
- We don't track profile visibility (they are all visible)
- We don't track email visibility (emails are never visible to other users)

**Comment by mikethicke** [comment]
https://github.com/MESH-Research/hc-custom/commit/7e9896d83e5e7fcdf36b0afa2f541da319cb42b6
