### ISSUE TITLE
implement Commons API endpoint for groups metadata

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#217]

**Comment by monotasker** [comment]
The data I need returned from requests to this endpoint:
- commons group id
- commons group name (readable)
- group url on commons
- group privacy (public, private, hidden?)
- group description
- group site url (if they have a site elsewhere)
- url for a group profile image (this isn't crucial, but it would be good for overlay journals, orgs, etc.)
- setting for who can upload submissions (anyone, group members, mods and admins only, admins only)
- setting for who can accept/approve submissions (group members, mods and admins, admins only)

**Comment by mikethicke** [comment]
Endpoints:

https://hcommons-dev.org/wp-json/commons/v1/groups/ 
https://hcommons-dev.org/wp-json/commons/v1/groups/:id

For bulk, can provide page and per_page parameters to control pagination. Default is 20/page.

Both use token authentication, so need to include authorization header with value `Bearer <token>` .

Sample response:

```
 {
        "id": 1004039,
        "name": "Group created by Barty",
        "url": "https://hcommons-dev.org/groups/group-created-by-barty/",
        "visibility": "public",
        "description": "tstaertasrewasr",
        "avatar": "https://hcommons-dev.org/app/plugins/buddypress/bp-core/images/mystery-group.png",
        "groupblog": "",
        "upload_roles": [
            "member",
            "moderator",
            "administrator"
        ],
        "moderate_roles": [
            "moderator",
            "administrator"
        ]
    }
```

Currently there is no UI for controlling upload and moderation permissions within a group. There should be a separate issue for implementing that functionality.

**Comment by mikethicke** [comment]
https://github.com/MESH-Research/hc-custom/commit/7e9896d83e5e7fcdf36b0afa2f541da319cb42b6
