### ISSUE TITLE
Recommendations and sample code for docx and ppt

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#293]

**Comment by koutiany** [comment]
3 libraries for .docx: 
1. python-docx: most commonly used one, footnote not included
2. docx2txt: no footnotes, but can get text out of imagine without any extra function written
3. mammoth: switch from docx to html, then parse it using beautiful soup; output could be a bit messy but footnote is for sure included.

Full updates see .md file on Github

**Comment by koutiany** [comment]
selected one library that fits all-- 'python-pptx', modified it by adding 'tesseract OCR' and 'timeit'
Full updates see .md file on GitHub
